server:
  port: 9291
spring:
  application:
    name: market-server
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: root
      username: root
      url: jdbc:mysql://localhost:3306/shop_admin?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true

  mvc:
    async:
      request-timeout: 20000
mybatis-plus:
  mapper-locations: classpath:com/rabbiter/market/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    cn.dingli.market.mapper: debug

